In [ ]:
import time
from datetime import datetime, timedelta
import os
import numpy as np
import pandas as pd
import requests


from web3 import Web3

from dotenv import load_dotenv
load_dotenv()

True

In [3]:
df = pd.read_csv('data/eth_blocks_2025-01-01_2026-02-15.csv')
df

,timestamp,height,hash,size,gas_limit,gas_used,transaction_count,base_fee_per_gas
0,2026-02-15 00:32:35 UTC,24458637,0x173fa6c45072b36b3b2489bf945c813f5eeb2fb7b7ce...,123436,59999886,17391909,108,35527943
1,2026-02-15 16:49:47 UTC,24463507,0xe0c7adb0bd468c81f23eb23627e60e5e373f1e1850da...,136110,59941351,24197479,272,46609559
2,2026-02-15 05:17:23 UTC,24460056,0xaf0bfcf9fecc2e7999c498184bbb9a36c50fcddd59a4...,206574,59941237,52959002,166,46207812
3,2026-02-15 14:31:35 UTC,24462819,0x8e9a8703ee7c65965eb2c4717ca74f9c48442f5d2542...,151227,59999886,42068893,263,33619778
4,2026-02-15 07:24:23 UTC,24460690,0xdca86811dbd9c17587a3b01bf72e16f1d633bc9d6ccb...,170208,59999886,46730062,481,48904977
...,...,...,...,...,...,...,...,...
2939758,2026-01-16 00:49:11 UTC,24243802,0xe03f9bf772619c82fc0a37bd64d25bbece1bbc3b9033...,236213,60000000,58358979,1156,40700653
2939759,2026-01-16 23:17:47 UTC,24250526,0xc3d889f810a1730f34473aaf4e6d463295d9180da2ee...,575739,60000000,59985849,178,29792259
2939760,2026-01-16 20:21:23 UTC,24249648,0x090cb4a592df450e965f775cbefd085620312cc003c4...,63704,60000000,12596083,154,50460437
2939761,2026-01-16 00:19:35 UTC,24243655,0xfc34e3be6633a3849bcc5e6155cf21ead59165682509...,83523,60000000,20000456,159,48073799
2939762,2026-01-16 15:01:59 UTC,24248054,0xb78ccceaa0db0826120537fad7fa6a2fd8c3b02fec78...,147203,60000000,27921037,396,84457986

In [4]:
df.describe()

,height,size,gas_limit,gas_used,transaction_count,base_fee_per_gas
count,2.939763e+06,2.939763e+06,2.939763e+06,2.939763e+06,2.939763e+06,2.939763e+06
mean,2.299577e+07,1.090783e+05,4.308254e+07,2.181120e+07,2.142717e+02,1.827983e+09
std,8.486366e+05,6.468409e+04,9.629040e+06,1.120064e+07,1.100360e+02,6.814647e+09
min,2.152589e+07,1.163000e+03,2.997070e+07,0.000000e+00,0.000000e+00,8.703865e+06
25%,2.226083e+07,7.005600e+04,3.596484e+07,1.432256e+07,1.490000e+02,1.561048e+08
50%,2.299577e+07,9.753000e+04,4.486800e+07,1.974043e+07,1.960000e+02,4.594324e+08
75%,2.373071e+07,1.336985e+05,4.504390e+07,2.730356e+07,2.560000e+02,1.250494e+09
max,2.446565e+07,1.956743e+06,6.011724e+07,6.005850e+07,2.753000e+03,8.255167e+11

In [6]:
print("=" * 60)
print("SHAPE")
print("=" * 60)
print(f"Rows: {df.shape[0]:,}  |  Columns: {df.shape[1]}")

print("\n" + "=" * 60)
print("COLUMNS & DTYPES")
print("=" * 60)
print(df.dtypes)

print("\n" + "=" * 60)
print("MEMORY USAGE")
print("=" * 60)
print(df.memory_usage(deep=True).to_string())
print(f"\nTotal: {df.memory_usage(deep=True).sum() / 1024**2:.2f} MB")

print("\n" + "=" * 60)
print("MISSING VALUES")
print("=" * 60)
missing = df.isnull().sum()
missing_pct = (missing / len(df) * 100).round(2)
missing_df = pd.DataFrame({"count": missing, "pct": missing_pct})
print(missing_df[missing_df["count"] > 0] if missing_df["count"].sum() > 0 else "No missing values")

print("\n" + "=" * 60)
print("DUPLICATES")
print("=" * 60)
print(f"Duplicate rows: {df.duplicated().sum():,}")


print("\n" + "=" * 60)
print("UNIQUE VALUES PER COLUMN")
print("=" * 60)
for col in df.columns:
    n = df[col].nunique()
    print(f"  {col}: {n:,} unique")

============================================================
SHAPE
============================================================
Rows: 2,939,763  |  Columns: 8

============================================================
COLUMNS & DTYPES
============================================================
timestamp              str
height               int64
hash                   str
size                 int64
gas_limit            int64
gas_used             int64
transaction_count    int64
base_fee_per_gas     int64
dtype: object

============================================================
MEMORY USAGE
============================================================
Index                      132
timestamp            235181040
height                23518104
hash                 361590849
size                  23518104
gas_limit             23518104
gas_used              23518104
transaction_count     23518104
base_fee_per_gas      23518104

Total: 703.70 MB

============================================================
MISSING VALUES
============================================================
No missing values

============================================================
DUPLICATES
============================================================
Duplicate rows: 0

============================================================
UNIQUE VALUES PER COLUMN
============================================================
  timestamp: 2,939,763 unique
  height: 2,939,763 unique
  hash: 2,939,763 unique
  size: 304,168 unique
  gas_limit: 83,549 unique
  gas_used: 2,794,940 unique
  transaction_count: 1,853 unique
  base_fee_per_gas: 2,935,682 unique

In [23]:
w3 = Web3(Web3.HTTPProvider(os.getenv("EL_NODE_URL")))

In [24]:
block = w3.eth.get_block("latest")
print(block.number)

24593524

In [ ]:
API_KEY = os.getenv("COINGECKO_API_KEY")

url = "https://api.coingecko.com/api/v3/simple/price"

params = {
    "ids": "ethereum",
    "vs_currencies": "usd"
}

headers = {
    "x-cg-demo-api-key": API_KEY
}

response = requests.get(url, params=params, headers=headers)

data = response.json()

eth_price = data["ethereum"]["usd"]

print(f"Current ETH price: ${eth_price}")

Current ETH price: $2075.69

In [ ]:
API_KEY = os.getenv("COINGECKO_API_KEY")

BASE_URL = "https://api.coingecko.com/api/v3/coins/ethereum/market_chart/range"

headers = {
    "x-cg-demo-api-key": API_KEY
}

start_date = datetime(2025, 3, 6)
end_date = datetime(2026, 3, 5)

chunk_days = 90

rows = []

current_start = start_date

while current_start < end_date:

    current_end = min(current_start + timedelta(days=chunk_days), end_date)
    print(f"Fetching data from {current_start.date()} to {current_end.date()}...")
    
    params = {
        "vs_currency": "usd",
        "from": int(current_start.timestamp()),
        "to": int(current_end.timestamp())
    }

    response = requests.get(BASE_URL, params=params, headers=headers)
    data = response.json()

    prices = data["prices"]
    market_caps = data["market_caps"]
    volumes = data["total_volumes"]

    for i in range(len(prices)):
        timestamp = prices[i][0]

        rows.append({
            "timestamp": timestamp,
            "datetime": pd.to_datetime(timestamp, unit="ms"),
            "price": prices[i][1],
            "market_cap": market_caps[i][1],
            "volume": volumes[i][1]
        })

    print(f"Loaded {current_start.date()} → {current_end.date()}")

    current_start = current_end
    time.sleep(1)

df = pd.DataFrame(rows)

df = df.sort_values("datetime").reset_index(drop=True)

print(df.head())

Fetching data from 2025-03-06 to 2025-06-04...
Loaded 2025-03-06 → 2025-06-04
Fetching data from 2025-06-04 to 2025-09-02...
Loaded 2025-06-04 → 2025-09-02
Fetching data from 2025-09-02 to 2025-12-01...
Loaded 2025-09-02 → 2025-12-01
Fetching data from 2025-12-01 to 2026-03-01...
Loaded 2025-12-01 → 2026-03-01
Fetching data from 2026-03-01 to 2026-03-05...
Loaded 2026-03-01 → 2026-03-05
       timestamp                datetime        price    market_cap  \
0  1741208564423 2025-03-05 21:02:44.423  2230.584518  2.693445e+11
1  1741212295383 2025-03-05 22:04:55.383  2236.766636  2.697674e+11
2  1741215784773 2025-03-05 23:03:04.773  2239.435736  2.699957e+11
3  1741219748187 2025-03-06 00:09:08.187  2244.935432  2.706242e+11
4  1741223086191 2025-03-06 01:04:46.191  2239.385254  2.699733e+11

         volume
0  2.335307e+10
1  2.253690e+10
2  2.218404e+10
3  2.222023e+10
4  2.234494e+10

In [17]:
df

,timestamp,datetime,price,market_cap,volume
0,1741208564423,2025-03-05 21:02:44.423,2230.584518,2.693445e+11,2.335307e+10
1,1741212295383,2025-03-05 22:04:55.383,2236.766636,2.697674e+11,2.253690e+10
2,1741215784773,2025-03-05 23:03:04.773,2239.435736,2.699957e+11,2.218404e+10
3,1741219748187,2025-03-06 00:09:08.187,2244.935432,2.706242e+11,2.222023e+10
4,1741223086191,2025-03-06 01:04:46.191,2239.385254,2.699733e+11,2.234494e+10
...,...,...,...,...,...
8731,1772640207826,2026-03-04 16:03:27.826,2150.392505,2.588748e+11,3.143937e+10
8732,1772643799382,2026-03-04 17:03:19.382,2143.077149,2.586854e+11,3.120427e+10
8733,1772647410540,2026-03-04 18:03:30.540,2147.037185,2.592250e+11,3.166291e+10
8734,1772650975057,2026-03-04 19:02:55.057,2162.208620,2.609615e+11,3.140737e+10
8735,1772654635663,2026-03-04 20:03:55.663,2179.303410,2.630594e+11,3.336981e+10

In [45]:
data

{'Data': [{'UNIT': 'HOUR',
   'TIMESTAMP': 1733950800,
   'OPEN': 3838.0773801909,
   'HIGH': 3838.5335069339,
   'LOW': 3817.32521945626,
   'CLOSE': 3833.13032121236,
   'VOLUME': 0,
   'QUOTE_VOLUME': 0},
  {'UNIT': 'HOUR',
   'TIMESTAMP': 1733954400,
   'OPEN': 3833.13032121236,
   'HIGH': 3848.14573277353,
   'LOW': 3826.47327068305,
   'CLOSE': 3839.44311558106,
   'VOLUME': 0,
   'QUOTE_VOLUME': 0},
  {'UNIT': 'HOUR',
   'TIMESTAMP': 1733958000,
   'OPEN': 3839.44311558106,
   'HIGH': 3851.41476879634,
   'LOW': 3828.22753640354,
   'CLOSE': 3834.39842449362,
   'VOLUME': 0,
   'QUOTE_VOLUME': 0},
  {'UNIT': 'HOUR',
   'TIMESTAMP': 1733961600,
   'OPEN': 3834.39842449362,
   'HIGH': 3839.83730811058,
   'LOW': 3810.68852970331,
   'CLOSE': 3820.52981580043,
   'VOLUME': 0,
   'QUOTE_VOLUME': 0},
  {'UNIT': 'HOUR',
   'TIMESTAMP': 1733965200,
   'OPEN': 3820.52981580043,
   'HIGH': 3826.42815633628,
   'LOW': 3800.68857808515,
   'CLOSE': 3807.94699811248,
   'VOLUME': 0,
   'QUOTE_VOLUME': 0},
  {'UNIT': 'HOUR',
   'TIMESTAMP': 1733968800,
   'OPEN': 3807.94699811248,
   'HIGH': 3885.48781375071,
   'LOW': 3806.44848077096,
   'CLOSE': 3883.31984115576,
   'VOLUME': 0,
   'QUOTE_VOLUME': 0},
  {'UNIT': 'HOUR',
   'TIMESTAMP': 1733972400,
   'OPEN': 3883.31984115576,
   'HIGH': 3949.9725609445,
   'LOW': 3854.17193878289,
   'CLOSE': 3938.97306533451,
   'VOLUME': 0,
   'QUOTE_VOLUME': 0},
  {'UNIT': 'HOUR',
   'TIMESTAMP': 1733976000,
   'OPEN': 3938.97306533451,
   'HIGH': 3946.55416137983,
   'LOW': 3897.66437194506,
   'CLOSE': 3909.942613989,
   'VOLUME': 0,
   'QUOTE_VOLUME': 0},
  {'UNIT': 'HOUR',
   'TIMESTAMP': 1733979600,
   'OPEN': 3909.942613989,
   'HIGH': 3946.62789003234,
   'LOW': 3904.8626910826,
   'CLOSE': 3928.32751348211,
   'VOLUME': 0,
   'QUOTE_VOLUME': 0},
  {'UNIT': 'HOUR',
   'TIMESTAMP': 1733983200,
   'OPEN': 3928.32751348211,
   'HIGH': 3938.82343066906,
   'LOW': 3911.37745865055,
   'CLOSE': 3938.59112627603,
   'VOLUME': 0,
   'QUOTE_VOLUME': 0},
  {'UNIT': 'HOUR',
   'TIMESTAMP': 1733986800,
   'OPEN': 3938.59112627603,
   'HIGH': 3943.1633683986,
   'LOW': 3905.14735107438,
   'CLOSE': 3905.36490662956,
   'VOLUME': 0,
   'QUOTE_VOLUME': 0},
  {'UNIT': 'HOUR',
   'TIMESTAMP': 1733990400,
   'OPEN': 3905.36490662956,
   'HIGH': 3923.21299405092,
   'LOW': 3904.16299057652,
   'CLOSE': 3913.45831392051,
   'VOLUME': 0,
   'QUOTE_VOLUME': 0},
  {'UNIT': 'HOUR',
   'TIMESTAMP': 1733994000,
   'OPEN': 3913.45831392051,
   'HIGH': 3937.64202923991,
   'LOW': 3913.3768439101,
   'CLOSE': 3925.00356734737,
   'VOLUME': 0,
   'QUOTE_VOLUME': 0},
  {'UNIT': 'HOUR',
   'TIMESTAMP': 1733997600,
   'OPEN': 3925.00356734737,
   'HIGH': 3926.42830008524,
   'LOW': 3894.0151585649,
   'CLOSE': 3926.42830008524,
   'VOLUME': 0,
   'QUOTE_VOLUME': 0},
  {'UNIT': 'HOUR',
   'TIMESTAMP': 1734001200,
   'OPEN': 3926.42830008524,
   'HIGH': 3937.24665028708,
   'LOW': 3905.5505259034,
   'CLOSE': 3912.73980590119,
   'VOLUME': 0,
   'QUOTE_VOLUME': 0},
  {'UNIT': 'HOUR',
   'TIMESTAMP': 1734004800,
   'OPEN': 3912.73980590119,
   'HIGH': 3962.8456746953,
   'LOW': 3912.80944260283,
   'CLOSE': 3957.92663948193,
   'VOLUME': 0,
   'QUOTE_VOLUME': 0},
  {'UNIT': 'HOUR',
   'TIMESTAMP': 1734008400,
   'OPEN': 3957.92663948193,
   'HIGH': 3978.4493700399,
   'LOW': 3923.20842577659,
   'CLOSE': 3943.65755697019,
   'VOLUME': 0,
   'QUOTE_VOLUME': 0},
  {'UNIT': 'HOUR',
   'TIMESTAMP': 1734012000,
   'OPEN': 3943.65755697019,
   'HIGH': 3984.91705054281,
   'LOW': 3933.12758926736,
   'CLOSE': 3984.85078991939,
   'VOLUME': 0,
   'QUOTE_VOLUME': 0},
  {'UNIT': 'HOUR',
   'TIMESTAMP': 1734015600,
   'OPEN': 3984.85078991939,
   'HIGH': 3988.48224366464,
   'LOW': 3941.73924248223,
   'CLOSE': 3960.40842255685,
   'VOLUME': 0,
   'QUOTE_VOLUME': 0},
  {'UNIT': 'HOUR',
   'TIMESTAMP': 1734019200,
   'OPEN': 3960.40842255685,
   'HIGH': 3987.18654531981,
   'LOW': 3932.59502307518,
   'CLOSE': 3936.25522309903,
   'VOLUME': 0,
   'QUOTE_VOLUME': 0},
  {'UNIT': 'HOUR',
   'TIMESTAMP': 1734022800,
   'OPEN': 3936.25522309903,
   'HIGH': 3967.89869319218,
   'LOW': 3932.52162572056,
   'CLOSE': 3963.68591045389,
   'VOLUME': 0,
   'QUOTE_VOLUME': 0},
  {'UNIT': 'HOUR',
   'TIMESTAMP': 1734026400,
   'OPEN': 3963.68591045389,
   'HIGH': 3967.361846503,
   'LOW': 3916.74998895328,
   'CLOSE': 3921.95716507061,
   'VOLUME': 0,
   'QUOTE_VOLUME': 0},
  {'UNIT': 'HOUR',
   'TIMESTAMP': 1734030000,
   'OPEN': 3921.95716507061,
   'HIGH': 3932.890140738,
   'LOW': 3856.7500326883,
   'CLOSE': 3871.81657565779,
   'VOLUME': 0,
   'QUOTE_VOLUME': 0},
  {'UNIT': 'HOUR',
   'TIMESTAMP': 1734033600,
   'OPEN': 3871.81657565779,
   'HIGH': 3901.41066658645,
   'LOW': 3867.40479081581,
   'CLOSE': 3885.37366128201,
   'VOLUME': 0,
   'QUOTE_VOLUME': 0},
  {'UNIT': 'HOUR',
   'TIMESTAMP': 1734037200,
   'OPEN': 3885.37366128201,
   'HIGH': 3895.67240655679,
   'LOW': 3864.41742102338,
   'CLOSE': 3868.06200430837,
   'VOLUME': 0,
   'QUOTE_VOLUME': 0},
  {'UNIT': 'HOUR',
   'TIMESTAMP': 1734040800,
   'OPEN': 3868.06200430837,
   'HIGH': 3887.62978152983,
   'LOW': 3837.50334201962,
   'CLOSE': 3883.84603831114,
   'VOLUME': 0,
   'QUOTE_VOLUME': 0},
  {'UNIT': 'HOUR',
   'TIMESTAMP': 1734044400,
   'OPEN': 3883.84603831114,
   'HIGH': 3887.8475419287,
   'LOW': 3860.29790964344,
   'CLOSE': 3882.90236736193,
   'VOLUME': 0,
   'QUOTE_VOLUME': 0},
  {'UNIT': 'HOUR',
   'TIMESTAMP': 1734048000,
   'OPEN': 3882.90236736193,
   'HIGH': 3906.34233282682,
   'LOW': 3876.14501581253,
   'CLOSE': 3890.77611136303,
   'VOLUME': 0,
   'QUOTE_VOLUME': 0},
  {'UNIT': 'HOUR',
   'TIMESTAMP': 1734051600,
   'OPEN': 3890.77611136303,
   'HIGH': 3890.76590551871,
   'LOW': 3854.84997776705,
   'CLOSE': 3884.09641812117,
   'VOLUME': 0,
   'QUOTE_VOLUME': 0},
  {'UNIT': 'HOUR',
   'TIMESTAMP': 1734055200,
   'OPEN': 3884.09641812117,
   'HIGH': 3927.76755733586,
   'LOW': 3880.3880914418,
   'CLOSE': 3908.08248843024,
   'VOLUME': 0,
   'QUOTE_VOLUME': 0},
  {'UNIT': 'HOUR',
   'TIMESTAMP': 1734058800,
   'OPEN': 3908.08248843024,
   'HIGH': 3941.30748209122,
   'LOW': 3903.54630700265,
   'CLOSE': 3934.03791946939,
   'VOLUME': 0,
   'QUOTE_VOLUME': 0},
  {'UNIT': 'HOUR',
   'TIMESTAMP': 1734062400,
   'OPEN': 3934.03791946939,
   'HIGH': 3936.42047013315,
   'LOW': 3913.17148034453,
   'CLOSE': 3917.43710584978,
   'VOLUME': 0,
   'QUOTE_VOLUME': 0},
  {'UNIT': 'HOUR',
   'TIMESTAMP': 1734066000,
   'OPEN': 3917.43710584978,
   'HIGH': 3931.77589128135,
   'LOW': 3906.29688037512,
   'CLOSE': 3909.92791418411,
   'VOLUME': 0,
   'QUOTE_VOLUME': 0},
  {'UNIT': 'HOUR',
   'TIMESTAMP': 1734069600,
   'OPEN': 3909.92791418411,
   'HIGH': 3926.83966271097,
   'LOW': 3888.95753659798,
   'CLOSE': 3888.95753738522,
   'VOLUME': 0,
   'QUOTE_VOLUME': 0},
  {'UNIT': 'HOUR',
   'TIMESTAMP': 1734073200,
   'OPEN': 3888.95753738522,
   'HIGH': 3903.86324858585,
   'LOW': 3873.37302122967,
   'CLOSE': 3885.76823446051,
   'VOLUME': 0,
   'QUOTE_VOLUME': 0},
  {'UNIT': 'HOUR',
   'TIMESTAMP': 1734076800,
   'OPEN': 3885.76823446051,
   'HIGH': 3904.08994354375,
   'LOW': 3876.1330594321,
   'CLOSE': 3896.90235570306,
   'VOLUME': 0,
   'QUOTE_VOLUME': 0},
  {'UNIT': 'HOUR',
   'TIMESTAMP': 1734080400,
   'OPEN': 3896.90235570306,
   'HIGH': 3903.85735165286,
   'LOW': 3876.33590944245,
   'CLOSE': 3890.70909727297,
   'VOLUME': 0,
   'QUOTE_VOLUME': 0},
  {'UNIT': 'HOUR',
   'TIMESTAMP': 1734084000,
   'OPEN': 3890.70909727297,
   'HIGH': 3906.16323786837,
   'LOW': 3873.22046949697,
   'CLOSE': 3904.76101115361,
   'VOLUME': 0,
   'QUOTE_VOLUME': 0},
  {'UNIT': 'HOUR',
   'TIMESTAMP': 1734087600,
   'OPEN': 3904.76101115361,
   'HIGH': 3923.23446992134,
   'LOW': 3903.00249365191,
   'CLOSE': 3903.00249369494,
   'VOLUME': 0,
   'QUOTE_VOLUME': 0},
  {'UNIT': 'HOUR',
   'TIMESTAMP': 1734091200,
   'OPEN': 3903.00249369494,
   'HIGH': 3931.19026702823,
   'LOW': 3902.33213212248,
   'CLOSE': 3929.59858846675,
   'VOLUME': 0,
   'QUOTE_VOLUME': 0},
  {'UNIT': 'HOUR',
   'TIMESTAMP': 1734094800,
   'OPEN': 3929.59858846675,
   'HIGH': 3934.67455023277,
   'LOW': 3909.5881941971,
   'CLOSE': 3925.05679635234,
   'VOLUME': 0,
   'QUOTE_VOLUME': 0},
  {'UNIT': 'HOUR',
   'TIMESTAMP': 1734098400,
   'OPEN': 3925.05679635234,
   'HIGH': 3951.75493477068,
   'LOW': 3919.61315641478,
   'CLOSE': 3951.3148348333,
   'VOLUME': 0,
   'QUOTE_VOLUME': 0},
  {'UNIT': 'HOUR',
   'TIMESTAMP': 1734102000,
   'OPEN': 3951.3148348333,
   'HIGH': 3968.38590251925,
   'LOW': 3880.87115349051,
   'CLOSE': 3887.95623864918,
   'VOLUME': 0,
   'QUOTE_VOLUME': 0},
  {'UNIT': 'HOUR',
   'TIMESTAMP': 1734105600,
   'OPEN': 3887.95623864918,
   'HIGH': 3934.41830220725,
   'LOW': 3882.36618385083,
   'CLOSE': 3915.24369984529,
   'VOLUME': 0,
   'QUOTE_VOLUME': 0},
  {'UNIT': 'HOUR',
   'TIMESTAMP': 1734109200,
   'OPEN': 3915.24369984529,
   'HIGH': 3945.75357766449,
   'LOW': 3908.6522963547,
   'CLOSE': 3940.95689569493,
   'VOLUME': 0,
   'QUOTE_VOLUME': 0},
  {'UNIT': 'HOUR',
   'TIMESTAMP': 1734112800,
   'OPEN': 3940.95689569493,
   'HIGH': 3940.89267119211,
   'LOW': 3914.11203092972,
   'CLOSE': 3914.11203092972,
   'VOLUME': 0,
   'QUOTE_VOLUME': 0},
  {'UNIT': 'HOUR',
   'TIMESTAMP': 1734116400,
   'OPEN': 3914.11203092972,
   'HIGH': 3926.40417724414,
   'LOW': 3912.83370864191,
   'CLOSE': 3918.49748954374,
   'VOLUME': 0,
   'QUOTE_VOLUME': 0},
  {'UNIT': 'HOUR',
   'TIMESTAMP': 1734120000,
   'OPEN': 3918.49748954374,
   'HIGH': 3934.98256426135,
   'LOW': 3912.19683295363,
   'CLOSE': 3918.1576943719,
   'VOLUME': 0,
   'QUOTE_VOLUME': 0},
  {'UNIT': 'HOUR',
   'TIMESTAMP': 1734123600,
   'OPEN': 3918.1576943719,
   'HIGH': 3918.71533005758,
   'LOW': 3894.0655144758,
   'CLOSE': 3903.86451538891,
   'VOLUME': 0,
   'QUOTE_VOLUME': 0},
  {'UNIT': 'HOUR',
   'TIMESTAMP': 1734127200,
   'OPEN': 3903.86451538891,
   'HIGH': 3907.77872632511,
   'LOW': 3894.53420788378,
   'CLOSE': 3897.97249027315,
   'VOLUME': 0,
   'QUOTE_VOLUME': 0},
  {'UNIT': 'HOUR',
   'TIMESTAMP': 1734130800,
   'OPEN': 3897.97249027315,
   'HIGH': 3913.21448404949,
   'LOW': 3896.51781955847,
   'CLOSE': 3907.08073946551,
   'VOLUME': 0,
   'QUOTE_VOLUME': 0},
  {'UNIT': 'HOUR',
   'TIMESTAMP': 1734134400,
   'OPEN': 3907.08073946551,
   'HIGH': 3926.61467305681,
   'LOW': 3896.62389325478,
   'CLOSE': 3906.71237917093,
   'VOLUME': 0,
   'QUOTE_VOLUME': 0},
  {'UNIT': 'HOUR',
   'TIMESTAMP': 1734138000,
   'OPEN': 3906.71237917093,
   'HIGH': 3944.46994400416,
   'LOW': 3906.49315979906,
   'CLOSE': 3926.35520842844,
   'VOLUME': 0,
   'QUOTE_VOLUME': 0},
  {'UNIT': 'HOUR',
   'TIMESTAMP': 1734141600,
   'OPEN': 3926.35520842844,
   'HIGH': 3926.70216801064,
   'LOW': 3904.10741496652,
   'CLOSE': 3913.14075697338,
   'VOLUME': 0,
   'QUOTE_VOLUME': 0},
  {'UNIT': 'HOUR',
   'TIMESTAMP': 1734145200,
   'OPEN': 3913.14075697338,
   'HIGH': 3921.81128531477,
   'LOW': 3905.39053353375,
   'CLOSE': 3911.80701866591,
   'VOLUME': 0,
   'QUOTE_VOLUME': 0},
  {'UNIT': 'HOUR',
   'TIMESTAMP': 1734148800,
   'OPEN': 3911.80701866591,
   'HIGH': 3918.05105173949,
   'LOW': 3907.22366447899,
   'CLOSE': 3915.73384314925,
   'VOLUME': 0,
   'QUOTE_VOLUME': 0},
  {'UNIT': 'HOUR',
   'TIMESTAMP': 1734152400,
   'OPEN': 3915.73384314925,
   'HIGH': 3921.16078227008,
   'LOW': 3909.60532824288,
   'CLOSE': 3920.32430475875,
   'VOLUME': 0,
   'QUOTE_VOLUME': 0},
  {'UNIT': 'HOUR',
   'TIMESTAMP': 1734156000,
   'OPEN': 3920.32430475875,
   'HIGH': 3935.00892241637,
   'LOW': 3918.90549343361,
   'CLOSE': 3930.77323801045,
   'VOLUME': 0,
   'QUOTE_VOLUME': 0},
  {'UNIT': 'HOUR',
   'TIMESTAMP': 1734159600,
   'OPEN': 3930.77323801045,
   'HIGH': 3933.26632026914,
   'LOW': 3920.62598495608,
   'CLOSE': 3921.06525808931,
   'VOLUME': 0,
   'QUOTE_VOLUME': 0},
  {'UNIT': 'HOUR',
   'TIMESTAMP': 1734163200,
   'OPEN': 3921.06525808931,
   'HIGH': 3931.09970900082,
   'LOW': 3917.79016900337,
   'CLOSE': 3926.33335453907,
   'VOLUME': 0,
   'QUOTE_VOLUME': 0},
  {'UNIT': 'HOUR',
   'TIMESTAMP': 1734166800,
   'OPEN': 3926.33335453907,
   'HIGH': 3926.36410495529,
   'LOW': 3911.76048874576,
   'CLOSE': 3911.93259592343,
   'VOLUME': 0,
   'QUOTE_VOLUME': 0},
  {'UNIT': 'HOUR',
   'TIMESTAMP': 1734170400,
   'OPEN': 3911.93259592343,
   'HIGH': 3912.15809808497,
   'LOW': 3887.69070674377,
   'CLOSE': 3897.904344637,
   'VOLUME': 0,
   'QUOTE_VOLUME': 0},
  {'UNIT': 'HOUR',
   'TIMESTAMP': 1734174000,
   'OPEN': 3897.904344637,
   'HIGH': 3905.33915447414,
   'LOW': 3891.93636873748,
   'CLOSE': 3895.1427456304,
   'VOLUME': 0,
   'QUOTE_VOLUME': 0},
  {'UNIT': 'HOUR',
   'TIMESTAMP': 1734177600,
   'OPEN': 3895.1427456304,
   'HIGH': 3898.53288450503,
   'LOW': 3866.58438203825,
   'CLOSE': 3868.75465104825,
   'VOLUME': 0,
   'QUOTE_VOLUME': 0},
  {'UNIT': 'HOUR',
   'TIMESTAMP': 1734181200,
   'OPEN': 3868.75465104825,
   'HIGH': 3875.03895837036,
   'LOW': 3847.59429800654,
   'CLOSE': 3862.89452468634,
   'VOLUME': 0,
   'QUOTE_VOLUME': 0},
  {'UNIT': 'HOUR',
   'TIMESTAMP': 1734184800,
   'OPEN': 3862.89452468634,
   'HIGH': 3892.56513340769,
   'LOW': 3862.91606074861,
   'CLOSE': 3886.93868237321,
   'VOLUME': 0,
   'QUOTE_VOLUME': 0},
  {'UNIT': 'HOUR',
   'TIMESTAMP': 1734188400,
   'OPEN': 3886.93868237321,
   'HIGH': 3893.09104844269,
   'LOW': 3878.33474338519,
   'CLOSE': 3889.03813028961,
   'VOLUME': 0,
   'QUOTE_VOLUME': 0},
  {'UNIT': 'HOUR',
   'TIMESTAMP': 1734192000,
   'OPEN': 3889.03813028961,
   'HIGH': 3896.91096013858,
   'LOW': 3869.43915550094,
   'CLOSE': 3893.08083734541,
   'VOLUME': 0,
   'QUOTE_VOLUME': 0},
  {'UNIT': 'HOUR',
   'TIMESTAMP': 1734195600,
   'OPEN': 3893.08083734541,
   'HIGH': 3897.5255590605,
   'LOW': 3843.16197106396,
   'CLOSE': 3859.14769894455,
   'VOLUME': 0,
   'QUOTE_VOLUME': 0},
  {'UNIT': 'HOUR',
   'TIMESTAMP': 1734199200,
   'OPEN': 3859.14769894455,
   'HIGH': 3862.61869195894,
   'LOW': 3828.39441923803,
   'CLOSE': 3832.72691135655,
   'VOLUME': 0,
   'QUOTE_VOLUME': 0},
  {'UNIT': 'HOUR',
   'TIMESTAMP': 1734202800,
   'OPEN': 3832.72691135655,
   'HIGH': 3860.77903308283,
   'LOW': 3831.31732729323,
   'CLOSE': 3859.69780778264,
   'VOLUME': 0,
   'QUOTE_VOLUME': 0},
  {'UNIT': 'HOUR',
   'TIMESTAMP': 1734206400,
   'OPEN': 3859.69780778264,
   'HIGH': 3865.82607318494,
   'LOW': 3826.50552315015,
   'CLOSE': 3831.88832082528,
   'VOLUME': 0,
   'QUOTE_VOLUME': 0},
  {'UNIT': 'HOUR',
   'TIMESTAMP': 1734210000,
   'OPEN': 3831.88832082528,
   'HIGH': 3856.52925205769,
   'LOW': 3831.88838261439,
   'CLOSE': 3848.42165665981,
   'VOLUME': 0,
   'QUOTE_VOLUME': 0},
  {'UNIT': 'HOUR',
   'TIMESTAMP': 1734213600,
   'OPEN': 3848.42165665981,
   'HIGH': 3866.73925912276,
   'LOW': 3839.44663203085,
   'CLOSE': 3861.54114537373,
   'VOLUME': 0,
   'QUOTE_VOLUME': 0},
  {'UNIT': 'HOUR',
   'TIMESTAMP': 1734217200,
   'OPEN': 3861.54114537373,
   'HIGH': 3875.15625051656,
   'LOW': 3855.8910219804,
   'CLOSE': 3870.07378415261,
   'VOLUME': 0,
   'QUOTE_VOLUME': 0},
  {'UNIT': 'HOUR',
   'TIMESTAMP': 1734220800,
   'OPEN': 3870.07378415261,
   'HIGH': 3874.63104809119,
   'LOW': 3856.31773384489,
   'CLOSE': 3864.34407521914,
   'VOLUME': 0,
   'QUOTE_VOLUME': 0},
  {'UNIT': 'HOUR',
   'TIMESTAMP': 1734224400,
   'OPEN': 3864.34407521914,
   'HIGH': 3894.06836968818,
   'LOW': 3863.34831606473,
   'CLOSE': 3889.61404992251,
   'VOLUME': 0,
   'QUOTE_VOLUME': 0},
  {'UNIT': 'HOUR',
   'TIMESTAMP': 1734228000,
   'OPEN': 3889.61404992251,
   'HIGH': 3891.83421076715,
   'LOW': 3881.97518176935,
   'CLOSE': 3883.37459483794,
   'VOLUME': 0,
   'QUOTE_VOLUME': 0},
  {'UNIT': 'HOUR',
   'TIMESTAMP': 1734231600,
   'OPEN': 3883.37459483794,
   'HIGH': 3885.632956681,
   'LOW': 3872.0782859065,
   'CLOSE': 3873.43795662219,
   'VOLUME': 0,
   'QUOTE_VOLUME': 0},
  {'UNIT': 'HOUR',
   'TIMESTAMP': 1734235200,
   'OPEN': 3873.43795662219,
   'HIGH': 3906.95389391962,
   'LOW': 3872.47013060398,
   'CLOSE': 3894.61499090793,
   'VOLUME': 0,
   'QUOTE_VOLUME': 0},
  {'UNIT': 'HOUR',
   'TIMESTAMP': 1734238800,
   'OPEN': 3894.61499090793,
   'HIGH': 3902.94935792078,
   'LOW': 3890.61079816048,
   'CLOSE': 3891.84336335299,
   'VOLUME': 0,
   'QUOTE_VOLUME': 0},
  {'UNIT': 'HOUR',
   'TIMESTAMP': 1734242400,
   'OPEN': 3891.84336335299,
   'HIGH': 3893.53283631363,
   'LOW': 3876.00744405099,
   'CLOSE': 3877.43032643679,
   'VOLUME': 0,
   'QUOTE_VOLUME': 0},
  {'UNIT': 'HOUR',
   'TIMESTAMP': 1734246000,
   'OPEN': 3877.43032643679,
   'HIGH': 3881.71561992017,
   'LOW': 3832.39179373909,
   'CLOSE': 3844.50723080063,
   'VOLUME': 0,
   'QUOTE_VOLUME': 0},
  {'UNIT': 'HOUR',
   'TIMESTAMP': 1734249600,
   'OPEN': 3844.50723080063,
   'HIGH': 3863.91036316982,
   'LOW': 3837.66457939082,
   'CLOSE': 3863.17054916713,
   'VOLUME': 0,
   'QUOTE_VOLUME': 0},
  {'UNIT': 'HOUR',
   'TIMESTAMP': 1734253200,
   'OPEN': 3863.17054916713,
   'HIGH': 3865.8462106262,
   'LOW': 3851.33821422236,
   'CLOSE': 3862.18567014738,
   'VOLUME': 0,
   'QUOTE_VOLUME': 0},
  {'UNIT': 'HOUR',
   'TIMESTAMP': 1734256800,
   'OPEN': 3862.18567014738,
   'HIGH': 3872.67907797275,
   'LOW': 3859.67645124974,
   'CLOSE': 3860.4772114713,
   'VOLUME': 0,
   'QUOTE_VOLUME': 0},
  {'UNIT': 'HOUR',
   'TIMESTAMP': 1734260400,
   'OPEN': 3860.4772114713,
   'HIGH': 3877.40837604303,
   'LOW': 3858.90361972984,
   'CLOSE': 3876.72951815096,
   'VOLUME': 0,
   'QUOTE_VOLUME': 0},
  {'UNIT': 'HOUR',
   'TIMESTAMP': 1734264000,
   'OPEN': 3876.72951815096,
   'HIGH': 3891.24193315571,
   'LOW': 3868.65423991564,
   'CLOSE': 3882.69516610865,
   'VOLUME': 0,
   'QUOTE_VOLUME': 0},
  {'UNIT': 'HOUR',
   'TIMESTAMP': 1734267600,
   'OPEN': 3882.69516610865,
   'HIGH': 3890.74184584229,
   'LOW': 3872.64359747861,
   'CLOSE': 3883.78240224511,
   'VOLUME': 0,
   'QUOTE_VOLUME': 0},
  {'UNIT': 'HOUR',
   'TIMESTAMP': 1734271200,
   'OPEN': 3883.78240224511,
   'HIGH': 3907.95842488065,
   'LOW': 3882.1751726257,
   'CLOSE': 3906.49547797981,
   'VOLUME': 0,
   'QUOTE_VOLUME': 0},
  {'UNIT': 'HOUR',
   'TIMESTAMP': 1734274800,
   'OPEN': 3906.49547797981,
   'HIGH': 3906.23619411296,
   'LOW': 3886.62306207922,
   'CLOSE': 3893.71977339825,
   'VOLUME': 0,
   'QUOTE_VOLUME': 0},
  {'UNIT': 'HOUR',
   'TIMESTAMP': 1734278400,
   'OPEN': 3893.71977339825,
   'HIGH': 3917.45938397538,
   'LOW': 3885.92032527602,
   'CLOSE': 3910.62635504049,
   'VOLUME': 0,
   'QUOTE_VOLUME': 0},
  {'UNIT': 'HOUR',
   'TIMESTAMP': 1734282000,
   'OPEN': 3910.62635504049,
   'HIGH': 3915.31668929223,
   'LOW': 3903.55668354743,
   'CLOSE': 3909.29553368892,
   'VOLUME': 0,
   'QUOTE_VOLUME': 0},
  {'UNIT': 'HOUR',
   'TIMESTAMP': 1734285600,
   'OPEN': 3909.29553368892,
   'HIGH': 3912.21739442301,
   'LOW': 3890.85101889775,
   'CLOSE': 3897.05930393674,
   'VOLUME': 0,
   'QUOTE_VOLUME': 0},
  {'UNIT': 'HOUR',
   'TIMESTAMP': 1734289200,
   'OPEN': 3897.05930393674,
   'HIGH': 3911.66823195497,
   'LOW': 3896.69912939742,
   'CLOSE': 3903.2914634352,
   'VOLUME': 0,
   'QUOTE_VOLUME': 0},
  {'UNIT': 'HOUR',
   'TIMESTAMP': 1734292800,
   'OPEN': 3903.2914634352,
   'HIGH': 3909.40939590536,
   'LOW': 3889.56013924902,
   'CLOSE': 3891.11686790804,
   'VOLUME': 0,
   'QUOTE_VOLUME': 0},
  {'UNIT': 'HOUR',
   'TIMESTAMP': 1734296400,
   'OPEN': 3891.11686790804,
   'HIGH': 3891.10700383841,
   'LOW': 3845.48679482462,
   'CLOSE': 3855.31960505252,
   'VOLUME': 0,
   'QUOTE_VOLUME': 0},
  {'UNIT': 'HOUR',
   'TIMESTAMP': 1734300000,
   'OPEN': 3855.31960505252,
   'HIGH': 3892.04961710619,
   'LOW': 3850.33511875511,
   'CLOSE': 3890.19661958232,
   'VOLUME': 0,
   'QUOTE_VOLUME': 0},
  {'UNIT': 'HOUR',
   'TIMESTAMP': 1734303600,
   'OPEN': 3890.19661958232,
   'HIGH': 3972.89391740706,
   'LOW': 3888.84129165576,
   'CLOSE': 3957.78276510868,
   'VOLUME': 0,
   'QUOTE_VOLUME': 0},
  {'UNIT': 'HOUR',

In [83]:
BASE_URL = "https://data-api.coindesk.com/index/cc/v1/historical/minutes"

headers = {
    "Authorization": f"Apikey {API_KEY}"
}

market = "cadli"
instrument = "ETH-USD"

start_date = datetime(2025, 1, 1)
end_date = datetime(2025, 1, 26, 21, 27, 0)

to_ts = int(end_date.timestamp())

limit = 2000

# rows = []

while True:

    params = {
        "market": market,
        "instrument": instrument,
        "limit": limit,
        "to_ts": to_ts,
        "groups": "OHLC,VOLUME",
        "aggregate": 1
    }

    r = requests.get(BASE_URL, params=params, headers=headers)
    data = r.json()

    batch = data["Data"]

    if not batch:
        break

    rows.extend(batch)

    oldest_ts = batch[0]["TIMESTAMP"]

    print("Downloaded until:", datetime.fromtimestamp(oldest_ts))

    if oldest_ts <= int(start_date.timestamp()):
        break
    to_ts = oldest_ts - 60

    time.sleep(1)


df = pd.DataFrame(rows)
df["datetime"] = pd.to_datetime(df["TIMESTAMP"], unit="s")
df = df.sort_values("datetime")

df = df[
    (df["datetime"] >= start_date) &
    (df["datetime"] <= end_date)
]

df = df.rename(columns={
    "OPEN": "open",
    "HIGH": "high",
    "LOW": "low",
    "CLOSE": "close",
    "VOLUME": "volume"
})

df = df.drop_duplicates(subset=["TIMESTAMP"])

print(df.shape)
print(df.head())
print(df.tail())

df.to_csv("eth_minutes_2025_2026.csv", index=False)

Downloaded until: 2025-01-25 12:08:00
Downloaded until: 2025-01-24 02:48:00
Downloaded until: 2025-01-22 17:28:00
Downloaded until: 2025-01-21 08:08:00
Downloaded until: 2025-01-19 22:48:00
Downloaded until: 2025-01-18 13:28:00
Downloaded until: 2025-01-17 04:08:00
Downloaded until: 2025-01-15 18:48:00
Downloaded until: 2025-01-14 09:28:00
Downloaded until: 2025-01-13 00:08:00
Downloaded until: 2025-01-11 14:48:00
Downloaded until: 2025-01-10 05:28:00
Downloaded until: 2025-01-08 20:08:00
Downloaded until: 2025-01-07 10:48:00
Downloaded until: 2025-01-06 01:28:00
Downloaded until: 2025-01-04 16:08:00
Downloaded until: 2025-01-03 06:48:00
Downloaded until: 2025-01-01 21:28:00
Downloaded until: 2024-12-31 12:08:00
(37288, 15)
          UNIT   TIMESTAMP         open         high          low  \
592892  MINUTE  1735689600  3332.507632  3332.575058  3331.424175
592893  MINUTE  1735689660  3332.575058  3333.252526  3332.369019
592894  MINUTE  1735689720  3333.237763  3336.691150  3333.237763
592895  MINUTE  1735689780  3336.670677  3336.788377  3333.966619
592896  MINUTE  1735689840  3334.550936  3336.225670  3334.497948

              close       volume  QUOTE_VOLUME  VOLUME_TOP_TIER  \
592892  3332.575058  2199.761001  7.329474e+06      1592.836367
592893  3333.237763  1760.051931  5.866020e+06      1158.938148
592894  3336.670677  3194.152240  1.065240e+07      2469.187420
592895  3334.550936  2574.240950  8.590584e+06      1482.093208
592896  3334.877579  1911.317672  6.375825e+06      1196.354155

        QUOTE_VOLUME_TOP_TIER  VOLUME_DIRECT  QUOTE_VOLUME_DIRECT  \
592892           5.307337e+06     445.434313         1.483383e+06
592893           3.862432e+06     443.397579         1.477068e+06
592894           8.234315e+06    1186.393800         3.955388e+06
592895           4.941583e+06     495.295426         1.651195e+06
592896           3.991170e+06     337.846276         1.126394e+06

        VOLUME_TOP_TIER_DIRECT  QUOTE_VOLUME_TOP_TIER_DIRECT  \
592892              444.176798                  1.479192e+06
592893              442.306659                  1.473430e+06
592894             1183.651850                  3.946180e+06
592895              494.815639                  1.649594e+06
592896              337.608351                  1.125600e+06

                  datetime
592892 2025-01-01 00:00:00
592893 2025-01-01 00:01:00
592894 2025-01-01 00:02:00
592895 2025-01-01 00:03:00
592896 2025-01-01 00:04:00
          UNIT   TIMESTAMP         open         high          low  \
554176  MINUTE  1737926580  3318.579308  3318.769961  3317.845190
554177  MINUTE  1737926640  3318.684504  3319.117990  3317.847432
554178  MINUTE  1737926700  3317.847432  3317.847432  3315.221577
554179  MINUTE  1737926760  3315.502610  3315.524675  3313.591170
554180  MINUTE  1737926820  3313.622435  3313.622435  3313.212482

              close       volume  QUOTE_VOLUME  VOLUME_TOP_TIER  \
554176  3318.684504  2374.269364  7.877923e+06      1494.122145
554177  3317.847432  1474.976919  4.894882e+06       692.444425
554178  3315.502610  2267.808621  7.520721e+06      1331.645614
554179  3313.622435  1255.823494  4.161759e+06       787.106496
554180  3313.245036  1438.747330  4.766329e+06       903.919467

        QUOTE_VOLUME_TOP_TIER  VOLUME_DIRECT  QUOTE_VOLUME_DIRECT  \
554176           4.957438e+06     418.253866         1.387822e+06
554177           2.297819e+06     218.197165         7.240976e+05
554178           4.414259e+06     381.374499         1.264194e+06
554179           2.608265e+06     269.659740         8.935496e+05
554180           2.994360e+06     243.407377         8.063980e+05

        VOLUME_TOP_TIER_DIRECT  QUOTE_VOLUME_TOP_TIER_DIRECT  \
554176              418.108133                  1.387338e+06
554177              218.105775                  7.237944e+05
554178              381.092084                  1.263258e+06
554179              269.575144                  8.932693e+05
554180              243.309797                  8.060744e+05

                  datetime
554176 2025-01-26 21:23:00
554177 2025-01-26 21:24:00
554178 2025-01-26 21:25:00
554179 2025-01-26 21:26:00
554180 2025-01-26 21:27:00

In [87]:
df = pd.DataFrame(rows)
df["datetime"] = pd.to_datetime(df["TIMESTAMP"], unit="s")
df = df.sort_values("datetime")

df = df.rename(columns={
    "OPEN": "open",
    "HIGH": "high",
    "LOW": "low",
    "CLOSE": "close",
    "VOLUME": "volume"
})

df = df.drop_duplicates(subset=["TIMESTAMP"])
df

,UNIT,TIMESTAMP,open,high,low,close,volume,QUOTE_VOLUME,VOLUME_TOP_TIER,QUOTE_VOLUME_TOP_TIER,VOLUME_DIRECT,QUOTE_VOLUME_DIRECT,VOLUME_TOP_TIER_DIRECT,QUOTE_VOLUME_TOP_TIER_DIRECT,datetime
592000,MINUTE,1735636080,3378.569323,3380.485797,3378.217773,3380.465130,1767.621519,5.974709e+06,969.995245,3.278723e+06,88.282421,298298.946808,87.683491,296273.130839,2024-12-31 09:08:00
592001,MINUTE,1735636140,3380.465130,3382.087644,3379.523548,3381.908966,2500.374313,8.453734e+06,1622.858775,5.487008e+06,133.230708,450299.577347,132.825178,448927.966293,2024-12-31 09:09:00
592002,MINUTE,1735636200,3381.908966,3383.238625,3381.428658,3382.847440,2221.012152,7.513716e+06,1247.153641,4.219135e+06,188.263742,636652.513877,184.458903,623698.905942,2024-12-31 09:10:00
592003,MINUTE,1735636260,3382.847440,3383.516298,3382.149028,3382.240800,1515.060300,5.125635e+06,867.835997,2.936108e+06,85.229725,288205.770504,85.036495,287551.856548,2024-12-31 09:11:00
592004,MINUTE,1735636320,3382.240800,3383.575566,3381.438189,3381.591191,1391.147431,4.706566e+06,819.917387,2.773771e+06,78.714229,266118.741873,78.559561,265595.298606,2024-12-31 09:12:00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1995,MINUTE,1771275360,1993.592348,1993.592436,1991.998667,1992.059820,2449.901777,4.879452e+06,1042.716522,2.076631e+06,169.015468,336451.804526,162.860668,324202.884306,2026-02-16 20:56:00
1996,MINUTE,1771275420,1992.059820,1993.146110,1991.808684,1992.881738,2614.963938,5.208310e+06,1282.120863,2.553640e+06,188.397666,375039.166557,187.591856,373435.571706,2026-02-16 20:57:00
1997,MINUTE,1771275480,1992.881738,1993.668483,1992.616035,1993.666354,2378.978058,4.741151e+06,1151.227796,2.294991e+06,157.786077,314198.056788,157.553098,313734.635499,2026-02-16 20:58:00
1998,MINUTE,1771275540,1993.666354,1994.365204,1993.646374,1993.967930,3014.687517,6.009953e+06,1534.545144,3.059086e+06,222.362850,443097.765103,218.906048,436208.518704,2026-02-16 20:59:00
1999,MINUTE,1771275600,1993.967930,1994.211019,1992.862987,1992.999824,3156.070330,6.287125e+06,1839.754313,3.664233e+06,412.359854,821274.905273,401.451104,799552.973113,2026-02-16 21:00:00

In [88]:
df['datetime'].min(), df['datetime'].max()

(Timestamp('2024-12-31 09:08:00'), Timestamp('2026-02-16 21:00:00'))

In [89]:
df.to_csv("data/eth_minutes_2025_2026.csv", index=False)

In [ ]:
df = df.sort_values("datetime").reset_index(drop=True)

# вычисляем разницу между соседними часами
df["diff_minutes"] = df["datetime"].diff().dt.total_seconds() / 60

# проверяем, есть ли пропуски
missing_hours = df[df["diff_minutes"] != 1]

if missing_hours.empty:
    print("Все часы на месте! Пропусков нет.")
else:
    print("Есть пропуски часов:")
    print(missing_hours[["datetime", "diff_minutes"]])

Есть пропуски часов:
             datetime  diff_minutes
0 2024-12-31 09:08:00           NaN